

name: Snap Build
on:
  workflow_call: 
  pull_request: # Triggers the workflow on pull requests targeting the main branch
                # It ensures builds will happen for every PR.
    types: [opened, synchronize, reopened]
    branches:
      - main 
  push:
    branches:
      - main # Whenever a commit is pushed to main
    tags:
      - 'v*-rc*' # Whenever a new version tag is pushed

jobs:
  call-snap-build-promotion-workflow:
    uses: tonysilva1989/test-my-snap/.github/workflows/build-publish.yaml@main
